# Generated by Django 5.0.6 on 2026-08-07 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('MEMBERSHIP', 'Membership Report'), ('ATTENDANCE', 'Attendance Report'), ('FINANCE', 'Financial Report'), ('DEPARTMENT', 'Department Report')], max_length=20)),
                ('file_format', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel')], default='PDF', max_length=10)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='accounts.branch')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_generated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
