# Generated by Django 5.0.6 on 2026-08-07 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('events', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('SUNDAY_SERVICE', 'Sunday Service'), ('BIBLE_STUDY', 'Bible Study'), ('PRAYER_MEETING', 'Prayer Meeting'), ('EVENT', 'Event'), ('OTHER', 'Other')], default='SUNDAY_SERVICE', max_length=20)),
                ('date', models.DateField()),
                ('qr_token', models.CharField(blank=True, help_text='Token embedded in the QR code for self check-in.', max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='accounts.branch')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_sessions', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(choices=[('MANUAL', 'Manual'), ('QR_CODE', 'QR Code')], default='MANUAL', max_length=10)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='members.member')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attendance.attendancesession')),
            ],
            options={
                'unique_together': {('session', 'member')},
            },
        ),
    ]
